global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "kkbox_serving_api"
    metrics_path: /metrics
    static_configs:
      # api_serving container name on the shared churn-network
      - targets: ["host.docker.internal:8000"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "kkbox-serving-api"
