{
 "title": "HTTP Layer Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Latency Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(serving_http_request_duration_seconds_sum[5m]))\r\n/\r\nsum(rate(serving_http_request_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(serving_http_requests_total{status_code=~\"5..\"}[5m]))\r\n/\r\nsum(rate(serving_http_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(serving_http_requests_total[1m])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "serving_http_requests_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "serving_http_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "In-flight Requests",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(serving_http_requests_in_progress)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(serving_http_request_duration_seconds_bucket[5m])) by (le)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}