{
 "title": "Feast Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Feast Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(serving_feast_online_fetch_duration_seconds_sum[5m]))\r\n/\r\nsum(rate(serving_feast_online_fetch_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feast Fetch Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(serving_feast_online_fetch_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feast P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(serving_feast_online_fetch_duration_seconds_bucket[5m])) by (le)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feast Error Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(serving_feast_online_fetch_total{status!=\"success\"}[5m]))\r\n/\r\nsum(rate(serving_feast_online_fetch_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}