{
 "title": "Model Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Average Batch Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(serving_batch_prediction_size_sum[5m])\r\n/\r\nrate(serving_batch_prediction_size_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(serving_prediction_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Churn Probability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(serving_prediction_churn_probability_sum[5m]))\r\n/\r\nsum(rate(serving_prediction_churn_probability_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heatmap probability distribution",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(serving_prediction_churn_probability_bucket[5m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Churn Prediction Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(serving_prediction_results_total[5m])) by (is_churn)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}