services:
  minio:
    image: minio/minio:latest
    container_name: disease_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - disease-trend-network
    command: server /data --console-address ':9001'
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    restart: always

  mc:
    image: minio/mc:latest
    container_name: disease_mc
    depends_on:
      - minio
    networks:
      - disease-trend-network
    entrypoint: >
      /bin/sh -c "
      sleep 5 &&
      /usr/bin/mc alias set minio http://minio:9000 minioadmin minioadmin &&
      /usr/bin/mc mb minio/disease-raw &&
      /usr/bin/mc mb minio/disease-processed &&
      exit 0
      "

volumes:
  minio_data:

networks:
  disease-trend-network:
    external: true